name: Outlook Covid Scraper
on: [push]
jobs:
  scrape:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - name: r Init
      uses: r-lib/actions/setup-r@v2
    - name: Run script
      run: Rscript covidscraper.R
    - name: Results
      run: |
        git add -A
        git commit -m "Data Updated" || echo "No changes to commit"
        git push origin || echo "No changes to commit"
