name: Outlook Covid Scraper
on: [push]
jobs:
  scrape:
    runs-on: macOS-11
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: r-lib/actions/setup-r@v2
      - name: phantomjs
        run: |
          brew tap homebrew/cask
          brew cask install phantomjs
      - name: r Packages
        run: Rscript -e 'install.packages(c("rvest", "janitor", "tidyverse", "lubridate", "xml2"))'
      - name: Run script
        run: Rscript covidscraper.R
      - name: Results
        run: |
          git add -A
          git commit -m 'Data Updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
